### ISSUE TITLE
RPubs links fail to open

### ISSUE THREAD

**Issue by b-kennedy0** [seanrife/statcheck-web#6]
All links to 'http://rpubs.com/michelenuijten/202816' fail to open. I found on the homepage "More information on this program is available here" and on the About/FAQ Page "see the statcheck manual."

**Comment by MicheleNuijten** [comment]
Thanks for letting us know! The link referred to an old version of the manual that I've deleted, but I forgot to update the link. The latest manual is published here: http://rpubs.com/michelenuijten/manualstatcheck. I'll update the link as well.

Thanks again!
Michèle
